### ISSUE TITLE
本地安装碰到的几个问题反馈，无法登录系统

### ISSUE THREAD

**Issue by smartxdcn** [chenstor/jizhang#1]
安装环境：群晖
apache2+php5.6+mariadb10
1、访问地址INSTALL，按要求修改支持条件，完成。
2、连接数据库，LOCALHOST居然不行，最后改成127.0.0.1连接成功
3、提示安装完成，进入系统登录页面，输入设置好的用户名和密码，点登录无响应。
4、随意输入用户名，提示帐户密码错误。
目前安装完成，但登录不了，浏览器CHROME

**Comment by chenstor** [comment]
> 安装环境：群晖
> apache2+php5.6+mariadb10
> 1、访问地址INSTALL，按要求修改支持条件，完成。
> 2、连接数据库，LOCALHOST居然不行，最后改成127.0.0.1连接成功
> 3、提示安装完成，进入系统登录页面，输入设置好的用户名和密码，点登录无响应。
> 4、随意输入用户名，提示帐户密码错误。
> 目前安装完成，但登录不了，浏览器CHROME

1. 建议使用MYSQL原版本，其他版本未测试；
2. localhost不成功，是本机的设置问题；
3. 点登录无反应，实际已经有结果，只是没有显示出来，按F12查看下具体错误

**Comment by smartxdcn** [comment]
> > 安装环境：群晖
> > apache2+php5.6+mariadb10
> > 1、访问地址INSTALL，按要求修改支持条件，完成。
> > 2、连接数据库，LOCALHOST居然不行，最后改成127.0.0.1连接成功
> > 3、提示安装完成，进入系统登录页面，输入设置好的用户名和密码，点登录无响应。
> > 4、随意输入用户名，提示帐户密码错误。
> > 目前安装完成，但登录不了，浏览器CHROME
> 
> 1. 建议使用MYSQL原版本，其他版本未测试；
> 2. localhost不成功，是本机的设置问题；
> 3. 点登录无反应，实际已经有结果，只是没有显示出来，按F12查看下具体错误

嗯，我重新调整了PHP设置，把各种插件功能全开上后，可以正常登录使用了，谢谢！
