### ISSUE TITLE
bug-list-new-2020-4-24

### ISSUE THREAD

**Issue by zjj8520** [chenstor/jizhang#17]
system.php?action=user
这个页面添加用户的时候表单都填写了 但是返回了参数不完整
修改用户信息的时候同样如此

**Comment by zjj8520** [comment]
这个问题我又重新定位了一遍在： 系统管理-> 用户管理 -> 修改用户的时候 关联项目选择所有项目的时候 会提示 参数不完整

**Comment by chenstor** [comment]
感谢，已经定位到问题。
