### ISSUE TITLE
批量记账不可用

### ISSUE THREAD

**Issue by SLT2** [chenstor/jizhang#8]
![QQ图片20190725155356](https://user-images.githubusercontent.com/13595296/61856301-70d87d00-aef4-11e9-8c25-4d7bf3b6c3ec.png)
反馈问题，批量记账正常记账，成功一直为0条。
PHP版本7.3.4，5.4版本也试过一样结果。

**Comment by SLT2** [comment]
经过调试，以下为修改成功的代码，供参考：
![QQ图片20190725163022](https://user-images.githubusercontent.com/13595296/61858907-a03db880-aef9-11e9-9e20-3b32a006fbc2.png)

**Comment by chenstor** [comment]
感谢，已经更新。
