### ISSUE TITLE
记账备注中含有繁体字会导致导出csv内容缺失。

### ISSUE THREAD

**Issue by SLT2** [chenstor/jizhang#9]
一个小型BUG，只要包含繁体字就会使导出内容该内容字段缺失。

Notice:  iconv(): Detected an illegal character in input string in \jizhang\date.php on line 375

![02](https://user-images.githubusercontent.com/13595296/63068364-8108d880-bf45-11e9-89a7-e0f98dadc3e3.png)
![01](https://user-images.githubusercontent.com/13595296/63068366-8108d880-bf45-11e9-8db6-8826d5c252f9.png)

**Comment by SLT2** [comment]
转成GBK可以修复此问题。

**Comment by chenstor** [comment]
已经确认，今天会修复。感谢反馈。
